import Head from 'next/head'
import Link from "next/link";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className='bg-bg min-h-screen'>
                <Link href={'schedule'}>
                    Розклад
                </Link>
            </main>
        </>
    )
}
